"use client";
import React, { useEffect, useState } from "react";
import { useUser } from "@clerk/clerk-react";
import { fetchAIOutputData } from "./OutputData";
import OutputTable from "./OutputTable";

const AIOutputTable = () => {
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { user } = useUser();

  useEffect(() => {
    const getData = async () => {
      setIsLoading(true);
      const result = await fetchAIOutputData();
      setData(result);
      setIsLoading(false);
    };
    getData();
  }, []);

  const filteredData = data.filter(
    (item) => item.createdBy === user?.primaryEmailAddress?.emailAddress
  );

  return (
    <div className="overflow-x-auto p-5 flex flex-col gap-2 bg-white m-2">
      <div className="mb-2">
        <h1 className="text-2xl font-bold mb-2">History</h1>
        <p className="text-gray-500">List of AI output generated by you</p>
      </div>
      {isLoading ? (
        <div className="flex justify-center items-center">
          <div className="loader"></div>
        </div>
      ) : (
        <OutputTable filteredData={filteredData} />
      )}
    </div>
  );
};

export default AIOutputTable;