"use client";
import { db } from "@/utils/db";
import { AIOutput } from "@/utils/Schema";
import React, { useEffect, useState } from "react";
import { useUser } from "@clerk/clerk-react";

const fetchAIOutputData = async () => {
  try {
    const data = await db.select().from(AIOutput).execute();
    return data;
  } catch (error) {
    console.error("Error fetching AI output data:", error);
    throw error;
  }
};

const limitWords = (text: string, wordLimit: number) => {
  return text.split(" ").slice(0, wordLimit).join(" ") + "...";
};

const AIOutputTable: React.FC = () => {
  const [data, setData] = useState<any[]>([]);
  const { user } = useUser();

  useEffect(() => {
    const getData = async () => {
      const result = await fetchAIOutputData();
      setData(result);
    };

    getData();
  }, []);

  const filteredData = data.filter(
    (item) => item.createdBy === user?.primaryEmailAddress?.emailAddress
  );

  return (
    <div className="overflow-x-auto p-5 flex flex-col gap-2 bg-white m-2">
      <div className="mb-2">
        <h1 className="text-2xl font-bold mb-2">History</h1>
        <p className="text-gray-500">List of AI output generated by you</p>
      </div>
      <div>
        <table className="min-w-full bg-white border border-gray-200">
          <thead>
            <tr>
              <th className="px-4 py-2 border-b">ID</th>
              <th className="px-4 py-2 border-b">Form Data</th>
              <th className="px-4 py-2 border-b">AI Response</th>
              <th className="px-4 py-2 border-b">Template Slug</th>
              <th className="px-4 py-2 border-b">Created By</th>
              <th className="px-4 py-2 border-b">Created At</th>
            </tr>
          </thead>
          <tbody>
            {filteredData.map((item) => (
              <tr key={item.id}>
                <td className="px-4 py-2 border-b">{item.id}</td>
                <td className="px-4 py-2 border-b">{item.formData}</td>
                <td className="px-4 py-2 border-b">
                  {limitWords(item.aiResponse, 10)}
                </td>
                <td className="px-4 py-2 border-b">{item.templateSlug}</td>
                <td className="px-4 py-2 border-b">{item.createdBy}</td>
                <td className="px-4 py-2 border-b">{item.createdAT}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default AIOutputTable;
